# -*- coding: utf-8 -*-
"""
王者荣耀国服全量英雄基准权威对照表 (CN Server Hero Manifest)
严格仅收录国服英雄，严禁收录任何国际服/海外服独立英雄。
专为运行时纵向差集比对设计，杜绝爬虫静默漏英雄。
"""

# 国服全量英雄权威名册：ename -> 档案基础元数据
CN_HERO_MANIFEST = {
    105: {"cname": "廉颇", "title": "正义爆轰", "hero_type": 3, "hero_type2": 0},
    106: {"cname": "小乔", "title": "恋之微风", "hero_type": 2, "hero_type2": 0},
    107: {"cname": "赵云", "title": "苍天翔龙", "hero_type": 1, "hero_type2": 4},
    108: {"cname": "墨子", "title": "和平守望", "hero_type": 2, "hero_type2": 1},
    109: {"cname": "妲己", "title": "魅力之狐", "hero_type": 2, "hero_type2": 0},
    110: {"cname": "嬴政", "title": "王者独尊", "hero_type": 2, "hero_type2": 0},
    111: {"cname": "孙尚香", "title": "千金重弩", "hero_type": 5, "hero_type2": 0},
    112: {"cname": "鲁班七号", "title": "机关造物", "hero_type": 5, "hero_type2": 0},
    113: {"cname": "庄周", "title": "逍遥梦幻", "hero_type": 3, "hero_type2": 0},
    114: {"cname": "刘禅", "title": "暴走机关", "hero_type": 3, "hero_type2": 0},
    115: {"cname": "高渐离", "title": "叛逆吟游", "hero_type": 2, "hero_type2": 0},
    116: {"cname": "阿轲", "title": "信念之刃", "hero_type": 4, "hero_type2": 0},
    117: {"cname": "钟无艳", "title": "野蛮之锤", "hero_type": 1, "hero_type2": 3},
    118: {"cname": "孙膑", "title": "逆流之时", "hero_type": 2, "hero_type2": 0},
    119: {"cname": "扁鹊", "title": "善恶怪医", "hero_type": 2, "hero_type2": 1},
    167: {"cname": "孙悟空", "title": "齐天大圣", "hero_type": 4, "hero_type2": 0},
    549: {"cname": "心魔六耳", "title": "孙悟空命格", "hero_type": 4, "hero_type2": 1},
    120: {"cname": "白起", "title": "最终兵器", "hero_type": 3, "hero_type2": 0},
    121: {"cname": "芈月", "title": "永恒之月", "hero_type": 2, "hero_type2": 1},
    123: {"cname": "吕布", "title": "无双之魔", "hero_type": 1, "hero_type2": 3},
    124: {"cname": "周瑜", "title": "铁血都督", "hero_type": 2, "hero_type2": 1},
    126: {"cname": "夏侯惇", "title": "不羁之风", "hero_type": 3, "hero_type2": 1},
    127: {"cname": "甄姬", "title": "洛神降临", "hero_type": 2, "hero_type2": 0},
    128: {"cname": "曹操", "title": "鲜血枭雄", "hero_type": 1, "hero_type2": 0},
    129: {"cname": "典韦", "title": "狂战士", "hero_type": 1, "hero_type2": 0},
    130: {"cname": "宫本武藏", "title": "剑圣", "hero_type": 1, "hero_type2": 4},
    131: {"cname": "李白", "title": "青莲剑仙", "hero_type": 4, "hero_type2": 0},
    132: {"cname": "马可波罗", "title": "远游之枪", "hero_type": 5, "hero_type2": 0},
    133: {"cname": "狄仁杰", "title": "断案大师", "hero_type": 5, "hero_type2": 0},
    134: {"cname": "达摩", "title": "拳僧", "hero_type": 1, "hero_type2": 3},
    135: {"cname": "项羽", "title": "霸王", "hero_type": 3, "hero_type2": 1},
    136: {"cname": "武则天", "title": "女帝", "hero_type": 2, "hero_type2": 0},
    139: {"cname": "老夫子", "title": "万古长明", "hero_type": 1, "hero_type2": 0},
    140: {"cname": "关羽", "title": "一骑当千", "hero_type": 1, "hero_type2": 3},
    141: {"cname": "貂蝉", "title": "绝世舞姬", "hero_type": 2, "hero_type2": 0},
    142: {"cname": "安琪拉", "title": "暗夜萝莉", "hero_type": 2, "hero_type2": 0},
    144: {"cname": "程咬金", "title": "热烈之斧", "hero_type": 3, "hero_type2": 0},
    146: {"cname": "露娜", "title": "月光之女", "hero_type": 4, "hero_type2": 2},
    148: {"cname": "姜子牙", "title": "封神者", "hero_type": 2, "hero_type2": 0},
    149: {"cname": "刘邦", "title": "双面君主", "hero_type": 3, "hero_type2": 2},
    150: {"cname": "韩信", "title": "国士无双", "hero_type": 4, "hero_type2": 0},
    152: {"cname": "王昭君", "title": "冰雪之华", "hero_type": 2, "hero_type2": 0},
    153: {"cname": "兰陵王", "title": "暗影刀锋", "hero_type": 4, "hero_type2": 0},
    154: {"cname": "花木兰", "title": "传说之刃", "hero_type": 1, "hero_type2": 0},
    156: {"cname": "张良", "title": "言灵之书", "hero_type": 2, "hero_type2": 0},
    157: {"cname": "不知火舞", "title": "明媚烈焰", "hero_type": 4, "hero_type2": 2},
    162: {"cname": "娜可露露", "title": "鹰之守护", "hero_type": 4, "hero_type2": 0},
    163: {"cname": "橘右京", "title": "神梦一刀", "hero_type": 4, "hero_type2": 1},
    166: {"cname": "亚瑟", "title": "圣骑之力", "hero_type": 1, "hero_type2": 3},
    168: {"cname": "牛魔", "title": "精英酋长", "hero_type": 3, "hero_type2": 0},
    169: {"cname": "后羿", "title": "半神之弓", "hero_type": 5, "hero_type2": 0},
    170: {"cname": "刘备", "title": "仁德义枪", "hero_type": 1, "hero_type2": 0},
    171: {"cname": "张飞", "title": "禁血狂兽", "hero_type": 3, "hero_type2": 0},
    173: {"cname": "李元芳", "title": "王都密探", "hero_type": 5, "hero_type2": 0},
    174: {"cname": "虞姬", "title": "森之风灵", "hero_type": 5, "hero_type2": 0},
    175: {"cname": "钟馗", "title": "虚灵城判", "hero_type": 3, "hero_type2": 2},
    178: {"cname": "杨戬", "title": "根源之目", "hero_type": 1, "hero_type2": 0},
    183: {"cname": "雅典娜", "title": "圣域余晖", "hero_type": 1, "hero_type2": 4},
    184: {"cname": "蔡文姬", "title": "天籁弦音", "hero_type": 2, "hero_type2": 0},
    186: {"cname": "太乙真人", "title": "炼金大师", "hero_type": 3, "hero_type2": 0},
    180: {"cname": "哪吒", "title": "桀骜炎枪", "hero_type": 1, "hero_type2": 3},
    190: {"cname": "诸葛亮", "title": "绝代智谋", "hero_type": 2, "hero_type2": 0},
    192: {"cname": "黄忠", "title": "燃魂重炮", "hero_type": 5, "hero_type2": 0},
    191: {"cname": "大乔", "title": "沧海之曜", "hero_type": 2, "hero_type2": 0},
    187: {"cname": "东皇太一", "title": "噬灭日蚀", "hero_type": 3, "hero_type2": 2},
    182: {"cname": "干将莫邪", "title": "淬命双剑", "hero_type": 2, "hero_type2": 0},
    189: {"cname": "鬼谷子", "title": "万物有灵", "hero_type": 2, "hero_type2": 0},
    193: {"cname": "铠", "title": "破灭刃锋", "hero_type": 1, "hero_type2": 3},
    196: {"cname": "百里守约", "title": "静谧之眼", "hero_type": 5, "hero_type2": 4},
    195: {"cname": "百里玄策", "title": "嚣狂之镰", "hero_type": 4, "hero_type2": 0},
    194: {"cname": "苏烈", "title": "不屈铁壁", "hero_type": 3, "hero_type2": 1},
    198: {"cname": "梦奇", "title": "入梦之灵", "hero_type": 3, "hero_type2": 2},
    179: {"cname": "女娲", "title": "至高创世", "hero_type": 2, "hero_type2": 0},
    501: {"cname": "明世隐", "title": "灵魂劫卜", "hero_type": 2, "hero_type2": 0},
    199: {"cname": "公孙离", "title": "幻舞玲珑", "hero_type": 5, "hero_type2": 0},
    176: {"cname": "杨玉环", "title": "霓裳风华", "hero_type": 2, "hero_type2": 0},
    502: {"cname": "裴擒虎", "title": "六合虎拳", "hero_type": 4, "hero_type2": 0},
    197: {"cname": "弈星", "title": "天元之弈", "hero_type": 2, "hero_type2": 0},
    503: {"cname": "狂铁", "title": "战车意志", "hero_type": 1, "hero_type2": 3},
    504: {"cname": "米莱狄", "title": "筑城者", "hero_type": 2, "hero_type2": 0},
    125: {"cname": "元歌", "title": "无间傀儡", "hero_type": 4, "hero_type2": 0},
    510: {"cname": "孙策", "title": "光明之海", "hero_type": 3, "hero_type2": 1},
    137: {"cname": "司马懿", "title": "寂灭之心", "hero_type": 4, "hero_type2": 2},
    509: {"cname": "盾山", "title": "无尽之盾", "hero_type": 3, "hero_type2": 0},
    508: {"cname": "伽罗", "title": "破魔之箭", "hero_type": 5, "hero_type2": 0},
    312: {"cname": "沈梦溪", "title": "爆弹怪猫", "hero_type": 2, "hero_type2": 0},
    507: {"cname": "李信", "title": "谋世之战", "hero_type": 1, "hero_type2": 0},
    513: {"cname": "上官婉儿", "title": "惊鸿之笔", "hero_type": 2, "hero_type2": 0},
    515: {"cname": "嫦娥", "title": "寒月公主", "hero_type": 2, "hero_type2": 1},
    511: {"cname": "猪八戒", "title": "无忧猛士", "hero_type": 3, "hero_type2": 0},
    529: {"cname": "盘古", "title": "破晓之神", "hero_type": 1, "hero_type2": 0},
    505: {"cname": "瑶", "title": "鹿灵守心", "hero_type": 2, "hero_type2": 0},
    506: {"cname": "云中君", "title": "流云之翼", "hero_type": 4, "hero_type2": 0},
    522: {"cname": "曜", "title": "星辰之子", "hero_type": 1, "hero_type2": 4},
    518: {"cname": "马超", "title": "冷晖之枪", "hero_type": 1, "hero_type2": 0},
    523: {"cname": "西施", "title": "幻纱之灵", "hero_type": 2, "hero_type2": 0},
    525: {"cname": "鲁班大师", "title": "神匠", "hero_type": 3, "hero_type2": 0},
    524: {"cname": "蒙犽", "title": "烈炮小子", "hero_type": 5, "hero_type2": 0},
    531: {"cname": "镜", "title": "破镜之刃", "hero_type": 4, "hero_type2": 0},
    527: {"cname": "蒙恬", "title": "秩序统将", "hero_type": 3, "hero_type2": 0},
    533: {"cname": "阿古朵", "title": "山林之子", "hero_type": 5, "hero_type2": 0},
    536: {"cname": "夏洛特", "title": "玫瑰剑士", "hero_type": 1, "hero_type2": 0},
    528: {"cname": "澜", "title": "鲨之猎刃", "hero_type": 4, "hero_type2": 1},
    537: {"cname": "司空震", "title": "雷霆之王", "hero_type": 1, "hero_type2": 2},
    155: {"cname": "艾琳", "title": "精灵之舞", "hero_type": 5, "hero_type2": 0},
    538: {"cname": "云缨", "title": "燎原之心", "hero_type": 1, "hero_type2": 4},
    540: {"cname": "金蝉", "title": "渡世行者", "hero_type": 2, "hero_type2": 0},
    542: {"cname": "暃", "title": "玉城之子", "hero_type": 4, "hero_type2": 0},
    534: {"cname": "桑启", "title": "萤火之旅", "hero_type": 2, "hero_type2": 0},
    548: {"cname": "戈娅", "title": "沙海飞舟", "hero_type": 5, "hero_type2": 0},
    521: {"cname": "海月", "title": "永夜之心", "hero_type": 2, "hero_type2": 0},
    544: {"cname": "赵怀真", "title": "自在之心", "hero_type": 1, "hero_type2": 0},
    545: {"cname": "莱西奥", "title": "火鹰船长", "hero_type": 5, "hero_type2": 0},
    564: {"cname": "姬小满", "title": "武道奇才", "hero_type": 1, "hero_type2": 0},
    514: {"cname": "亚连", "title": "追忆之刃", "hero_type": 1, "hero_type2": 3},
    159: {"cname": "朵莉亚", "title": "人鱼之歌", "hero_type": 2, "hero_type2": 0},
    563: {"cname": "海诺", "title": "命运之引", "hero_type": 1, "hero_type2": 2},
    519: {"cname": "敖隐", "title": "凌霄真龙", "hero_type": 5, "hero_type2": 0},
    517: {"cname": "大司命", "title": "肃归之戈", "hero_type": 1, "hero_type2": 0},
    582: {"cname": "元流之子(法师)", "title": "万妙之心", "hero_type": 2, "hero_type2": 0},
    581: {"cname": "元流之子(坦克)", "title": "止戈之道", "hero_type": 3, "hero_type2": 0},
    577: {"cname": "少司缘", "title": "聆愿之祝", "hero_type": 2, "hero_type2": 0},
    558: {"cname": "影", "title": "黯羽东君", "hero_type": 1, "hero_type2": 0},
    177: {"cname": "苍", "title": "苍狼末裔", "hero_type": 5, "hero_type2": 0},
    550: {"cname": "空空儿", "title": "笑面诡手", "hero_type": 1, "hero_type2": 0},
    584: {"cname": "元流之子(射手)", "title": "沉舟之志", "hero_type": 5, "hero_type2": 0},
    151: {"cname": "孙权", "title": "定旌之谋", "hero_type": 5, "hero_type2": 0},
    172: {"cname": "蚩奼", "title": "五兵之主", "hero_type": 1, "hero_type2": 0},
    585: {"cname": "元流之子(辅助)", "title": "守望之诺", "hero_type": 2, "hero_type2": 0},
    188: {"cname": "大禹", "title": "鼎镇山河", "hero_type": 3, "hero_type2": 0},
    583: {"cname": "元流之子(刺客)", "title": "凌绝之锋", "hero_type": 4, "hero_type2": 0},
    547: {"cname": "卢雅那", "title": "蛇焰使者", "hero_type": 5, "hero_type2": 0},
    138: {"cname": "王维", "title": "空山遗客", "hero_type": 2, "hero_type2": 0},
}

def get_manifest_dict():
    """获取国服基准英雄字典 (ename -> hero_info)"""
    return CN_HERO_MANIFEST.copy()

def get_manifest_list():
    """获取国服基准英雄列表"""
    return [
        {"ename": ename, **info}
        for ename, info in CN_HERO_MANIFEST.items()
    ]

def get_manifest_names():
    """获取国服基准英雄中文名集合"""
    return {h["cname"] for h in CN_HERO_MANIFEST.values()}
